version: '2.1'

services: 
  docker-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass123
      - MYSQL_DATABASE=test1
      - MYSQL_USER=foobar
      - MYSQL_PASSWORD=foobar
      - MYSQL_HOST=localhost
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootpass123 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:mysql://docker-mysql:3306/test1 -schemas=test1 -user=foobar -password=foobar migrate
    volumes:
     - "./sql:/flyway/sql"
    depends_on:
      docker-mysql:
        condition: service_healthy
